### PR TITLE
Replace language-container deployer with the common implementation in python-extension-common

### LINKED ISSUE #118: Replace  language-container deployer with the common implementation in python-extension-common
We extracted a common implementation for the language-container deployer to the python-extension-common repo.
We need to replace the implementation with common by importing and configuring it.

## Tasks:

- [language_container_deployer.py](https://github.com/exasol/sagemaker-extension/blob/main/exasol_sagemaker_extension/deployment/language_container_deployer.py) can be removed, because it is completely implemented in python-extension-common
- [language_container_deployer_cli.py](https://github.com/exasol/sagemaker-extension/blob/main/exasol_sagemaker_extension/deployment/language_container_deployer_cli.py) can be removed, because it is completely implemented in python-extension-common
- [deploy.py](https://github.com/exasol/sagemaker-extension/blob/main/exasol_sagemaker_extension/deploy.py) needs its imports changed to python-extension-common
- [sme_language_container_deployer.py](https://github.com/exasol/sagemaker-extension/blob/main/exasol_sagemaker_extension/deployment/sme_language_container_deployer.py) needs its imports changed to python-extension-common
- We probably need a test, that at least checks, if the path defined sme_language_container_deployer.py work with deployer cli and SmeLanguageContainerDeployer

### PR DESCRIPTION
**Pull request by Shmuma**
Closes #118 

- [x] add dependency on python-extension-common
- [x] refactor the code to use it
- [x] implement tests
- [x] removed bucketfs_operations and exasol-bucketfs dep

### CODE REVIEW

**Comment by ahsimb** [comment]
I am not sure the unit test is needed, as it practically replicates [this](https://github.com/exasol/python-extension-common/blob/c92243bc39daa638bb153bfca0e229d96e1e81e4/test/unit/deployment/test_language_container_deployer.py#L48) test in the python-extension-common

**Comment by ahsimb** [comment]
We should also change the documentation since we have new parameters in the cli. Plus the usual changelog.

**Comment by Shmuma** [comment]
> I am not sure the unit test is needed, as it practically replicates [this](https://github.com/exasol/python-extension-common/blob/c92243bc39daa638bb153bfca0e229d96e1e81e4/test/unit/deployment/test_language_container_deployer.py#L48) test in the python-extension-common

Yes, I used it for the inspiration, but unit test I added is working on a different level - we're checking the functionality of the subclass of the class provided by python-extension-common. As they are now live in separate repos/packages, superclass might change the behaviour without updating the subclass. The test is basic, but I think it is better than nothing

**Comment by Shmuma** [comment]
> We should also change the documentation since we have new parameters in the cli. Plus the usual changelog.

Hm, what new parameter do you mean? I added no new parameters.

Good point about the changelog, will add.

**Comment by ahsimb** [comment]
The new parameters are related to SaaS.

**Comment by Shmuma** [comment]
Created a separate task to update the documentation: https://github.com/exasol/sagemaker-extension/issues/122

**Review by ahsimb — DISMISSED** [review]

**Review by ahsimb — APPROVED** [review]

**Pull request merged**
